export default function Head() {
  return (
    <>
      <title>ChatGPT Messenger </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://oddblogger.com/wp-content/uploads/2023/05/ChatGPT-Logo-PNG-1.png"
      />
    </>
  );
}
